name: clip_sync
description: "Cross-platform clipboard sync over LAN"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.5

  # Networking
  multicast_dns: ^0.3.3
  web_socket_channel: ^3.0.3

  # Utilities
  uuid: ^4.5.2
  crypto: ^3.0.7
  shared_preferences: ^2.5.5
  path_provider: ^2.1.5
  win32: ^5.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
